import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Header from "@/components/ui/header/header";
import axiosClient from "@/lib/axios-client";
import AuthProvider from "@/providers/auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ticketing app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const { data } = {
  //   data: { currentUser: { id: "amrit", email: "someon@gmail.com", iat: 43 } },
  // };
  const { data } = (await axiosClient().get("/api/users/currentuser")) as {
    data: { currentUser: { email: string; id: string; iat: number } };
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header currentUser={data.currentUser} />
        <AuthProvider currentUser={data.currentUser}>{children} </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
